### ISSUE TITLE
1950 Fields List Mistakenly Retains “Dwelling No.”

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#147]
Eve is tidying up the 1950 census form with an eye towards disseminating it to other installations.
The 1950 census doesn’t have dwelling numbers.  The 1950 census form doesn’t have a box for dwelling numbers.  However there’s one remnant (left over from the 1940 census) that still has Dwelling No., the Fields list, below.  Could you remove it?
![83EE9C4E-BDCA-4513-BCC3-8AB2E0B676AF](https://user-images.githubusercontent.com/114665933/207156191-e1d307db-ec47-4887-94db-26a7b31fc102.jpeg)

**Comment by PatientRowan** [comment]
Corollary: “Dwelling” (always empty) displays on the public-view summary record:
![E61FB781-08E9-4A33-8440-F0E43BD11B89](https://user-images.githubusercontent.com/114665933/211194791-02e19c4b-1560-4e77-b23b-bc3d7602c4cf.jpeg)

**Comment by dfurber** [comment]
Fixed it.

**Comment by PatientRowan** [comment]
Thank you.  I’m writing this reply to remind myself that I have to change our documentation’s screen shot and text now.

**Comment by PatientRowan** [comment]
I’m still seeing the empty Dwelling box in the public view.  I think we want to display the Serial No. instead.

**Comment by PatientRowan** [comment]
This morning I’m also still seeing Dwelling No. on the staff-view fields list.  Almost as if you have a newer version that I’m not running yet.

**Comment by PatientRowan** [comment]
Dang, so close!! Dwelling is gone, thank you, but I had not seen before that Ward is showing.  But 1950 doesn’t have Wards either.
