### ISSUE TITLE
Indexing Last Name Starts With

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#319]
Last name starts with is acting funny today:
![IMG_0607](https://github.com/historyforge/historyforge/assets/114665933/c7b270b2-e737-42a6-8873-f65086b4ad07)
I had a Krum; I expected all the Krums to come before all the Krumrine, Krumhansl, etc.  The program seems to stop at the letters that I have entered (k-r-u-m) and then arranged them in first name order.

**Comment by dfurber** [comment]
It was doing that because what I did to teach it to index on the matched name rather than the canonical name forgot to put a space between the last name and the first name. Should be working now.

**Comment by PatientRowan** [comment]
I’m still seeing this:
![IMG_0610](https://github.com/historyforge/historyforge/assets/114665933/825f3da0-24a2-4d3f-97a4-d326adc43961)

**Comment by PatientRowan** [comment]
Last name starts with Bell gets worse the further you look (I was looking for Shirley Bell):
![IMG_0618](https://github.com/historyforge/historyforge/assets/114665933/d5a051ea-8d8c-4080-810d-6997b4d54c32)

**Comment by PatientRowan** [comment]
A couple of Boda-related persons died recently and I searched them in HistoryForge.  I thought that the index of the search on Last name starts with Boda was a short, clean, simple display of the problems with ordering:
![IMG_0645](https://github.com/historyforge/historyforge/assets/114665933/1fcab220-7f2b-4bcf-a17b-9e8b8c2b40ac)

**Comment by dfurber** [comment]
Yeah the problem is that the "sortable name" does not have a comma between last name and first name, so that "Boda Mi" comes after "Bodamer".

**Comment by dfurber** [comment]
It's something I have to fix (coming later today) and then update all the existing records to save their "sortable name" to have commas instead of spaces joining the name parts.

**Comment by PatientRowan** [comment]
Looking for a Krum, came across these Krumhansl nested among them:
![Screen Shot 2024-03-18 at 9 59 13 AM](https://github.com/historyforge/historyforge/assets/114665933/cace739b-cfc7-4084-b20c-ba80990ec122)

**Comment by dfurber** [comment]
At last, it was a bizarre string collation sort issue: https://stackoverflow.com/a/63881163

**Comment by PatientRowan** [comment]
This is beautiful, Dave, and such a relief, thank you.
     I was fretting over this just the other day on the 1950 census.  This old lady had a Blank on the census where her first name should have been, and I had to figure out what her first name was.  It wasn’t very hard. Her last name was Hoy.   She was the widow of a wealthy Cornell bigwig, David Hoy, as in that little gem of a ballpark Hoy Field that the university recently torn down.  One of the steps I took was to search Last name starts with Hoy.  The search results gave David and their son David Junior and then a lot of Hoyts before returning at a random point to Hoy, Silence.
     That’s right.  Her first name was Silence.  I imagine the doorstep interview: “And what is your first name, Mrs. Hoy?”  — “Silence.”  She might have been a bit of a battle axe and the enumerator just bailed out of the interaction.  She died a couple years later in Florida.
