### ISSUE TITLE
Google Maps Goes to Groton, CT Instead of Groton, NY

### ISSUE THREAD

**Issue by PatientRowan** [historyforge/historyforge#475]
@EveSnyder asked me to post this.  I’m working on 1950 Groton and doing a little sub-sample of building records.  One step is to use Google Maps to look at the residence and see if it plausibly could have existed in 1950.  If it’s a newer building, I don’t make a building records.
    To search Google Maps, I use the app on my iPad.  Here is a screen shot of my search on 201 Elm St Groton:

![Image](https://github.com/user-attachments/assets/8bf1d994-cb3d-4966-9aa1-70cea5f100a1)

**Comment by PatientRowan** [comment]
But when I submit "201 Elm St Groton, Town of Groton" on a HistoryForge building record, here's how the automatic mapping comes out:
<img width="1169" height="602" alt="Image" src="https://github.com/user-attachments/assets/997e8021-3712-462d-92a3-4e63418cf0aa" />

That's Groton, Connecticut.

This doesn't happen on every Groton New York address but it does seem to happen a lot.  I correct it in HistoryForge by copying the latitute/longitude from the Google Maps knowledge panel.

Would it be possible for HistoryForge to use a different version of Google Maps?

**Comment by dfurber** [comment]
Since the building address doesn't have a state component, I will use the state from Settings -> Census Record Defaults.

**Comment by dfurber** [comment]
Fixed by https://github.com/historyforge/historyforge/pull/482

**Comment by PatientRowan** [comment]
I’ll give it a try as soon as I can, thank you.

**Comment by PatientRowan** [comment]
Status Fixed, not published.  I have been working in Groton recently and am still encountering this problem, especially along Main Street in Groton NY.
A lot of Main Street in Groton NY got torn down when the SCM factory closed, while Groton CT doesn't map at all onto NY addresses.  The program seems to choose someplace central in Groton CT.  I would prefer someplace central in Groton NY.

**Comment by dfurber** [comment]
I think the missing piece was to add a check that if the returned location is more than 50km from the locality's center, then use the locality's center instead of the returned location. Just did that.
